set -g prefix `
unbind C-b
bind ` send-prefix
set-option -g mouse on

unbind '"'
bind - splitw -v -c '#{pane_current_path}' # 垂直方向新增面板，默认进入当前目录
unbind %
bind \\ splitw -h -c '#{pane_current_path}' # 水平方向新增面板，默认进入当前目录

set -g base-index 1 # 设置窗口的起始下标为1
set -g pane-base-index 1 # 设置面板的起始下标为1

set -g status-interval 1 # 状态栏刷新时间
set -g status-justify left # 状态栏列表左对齐
setw -g monitor-activity on # 非当前窗口有内容更新时在状态栏通知

# 状态栏整体背景和文字 (VS Code Status Bar Background)
set -g status-style "bg=#1e1e1e,fg=#cccccc"

# 左侧 Session 名称 (加粗，略带蓝色)
set -g status-left "#[fg=#007acc,bold] #S "

# 右侧 时间/日期
set -g status-right "#[fg=#858585] %H:%M #[fg=#858585]| %Y-%m-%d "

# 当前激活窗口标签 (背景为蓝色，文字为白色)
setw -g window-status-current-style "bg=#007acc,fg=#ffffff,bold"
setw -g window-status-current-format " #I:#W "

# 非激活窗口标签
setw -g window-status-style "fg=#858585"
setw -g window-status-format " #I:#W "

# 设置选中后的高亮颜色：背景为浅灰色 (#444444 或 colour240)，文字保持白色或自动
set -g mode-style "bg=#444444,fg=#ffffff"

set-option -sg escape-time 10

# TPM
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# 启用 pane 路径恢复（这是重点）
set -g @resurrect-capture-pane-contents 'off'
set -g @resurrect-save-pane-cwd 'on'

# 不恢复进程（避免恢复 vim / ssh / go run 等）
set -g @resurrect-processes 'false'

# 仅保存结构，不做进程级恢复
set -g @resurrect-capture-pane-contents 'off'

set -g @continuum-restore 'on'
set -g @continuum-save-interval '10'

run '~/.tmux/plugins/tpm/tpm'
